Add automatic testing with csmith and spike
Enables automatic testing by generating a randomized C program with csmith,
compiling it for x86_64 and RISC-V. The latter is run on SPIKE and RI5CY (with
either verilator or vsim). The programs always compute a checksum which is used
to judge whether there were any problems with executing them.

Csmith needs to be on the PATH or set via $CSMITH and $CSMITH_INCLUDE needs to
point to the header files provided by csmith.

Csmith doesn't guarantee that generated programs halt, so a small
$CSMITH_TIMEOUT_REF timeout value can be configured to filter those programs
out. Sometimes the simulator gets stuck which is why we have
$CSMITH_TIMEOUT_VSIM and $CSMITH_TIMEOUT_VERI for vsim and verilator
respectively.

The +vcd argument now also works for verilator (by hacking around verilators
limitation with compile time macros). It's mainly useful to disable vcd's since
they noticeably slow down simulation speed.

tb/core/.clang-format:
Update to align consecutive statements.

tb/core/Makefile:
New csmith targets. The command `make csmith-loop` generates and runs programs
until encountering an error. The seed can be used to reconstruct the probelmatic
executable. Also there is the now support for +vcd with verilator.

tb/core/tb_top:
Remove the small infinite loop program when providing no firmware. Can be
annoying when trying to debug.

tb/core/tb_top_verilator:
Add ifdefs to handle vcd dumping

tb/core/csmith/link:
Default linkerscript with some changes: we put the entry point at 0x0, the
vector table at 0x200 and the .text section at 0x10000. Runs both with spike and
the ri5cy testbench equally well.

tb/core/csmith/riscv-isa-sim:
Patched spike to 1. abort if we execute too many instructions 2. exit if we hit
ecall or ebreak 3. print to stdout when writing to 0x10000000. Csmith doesn't
generate ecall/ebreak anyway so thats why we use it to signal the end of test.
This could be done better.

tb/core/csmith/syscalls:
Minimalistic syscalls implementation.

diff --git a/tb/core/Makefile b/tb/core/Makefile
--- a/tb/core/Makefile
+++ b/tb/core/Makefile
@@ -10,22 +10,20 @@
 
 # Author: Robert Balas (balasr@student.ethz.ch)
 # Description: All in one. Uses parts of picorv32's makefile for handling the
-# firmware
-
-VERILATOR		= verilator
-VERI_FLAGS              =
-VERI_DIR                = cobj_dir
+# firmware and handling csmith programs
 
 MAKE			= make
 CTAGS			= ctags
+CSMITH			= csmith
 
+# vsim configuration
 VVERSION                = "10.7b"
 
 VLIB			= vlib-$(VVERSION)
 VWORK			= work
 
 VLOG			= vlog-$(VVERSION)
-VLOG_FLAGS		= -pedanticerrors
+VLOG_FLAGS		= -pedanticerrors -floatparameters
 VLOG_LOG                = vloggy
 
 VOPT			= vopt-$(VVERSION)
@@ -38,6 +36,15 @@ VSIM_DEBUG_FLAGS	= -debugdb
 VSIM_GUI_FLAGS          = -gui -debugdb
 VSIM_SCRIPT             = vsim.tcl
 
+# verilator configuration
+VERILATOR		= verilator
+VERI_FLAGS              =
+VERI_COMPILE_FLAGS      =
+VERI_TRACE              =
+VERI_DIR                = cobj_dir
+VERI_CFLAGS             = -O2
+
+# RTL source files
 RTLSRC_HOME             := ../..
 RTLSRC_TB_PKG		:=
 RTLSRC_TB_TOP		:= tb_top.sv
@@ -46,15 +53,17 @@ RTLSRC_VERI_TB          := $(filter-out tb_top.sv, $(wildcard *.sv))
 RTLSRC_INCDIR           := $(RTLSRC_HOME)/rtl/include
 RTLSRC_PKG		:= $(addprefix $(RTLSRC_HOME)/rtl/include/,\
 				apu_core_package.sv riscv_defines.sv \
-				riscv_tracer_defines.sv riscv_config.sv)
+				riscv_tracer_defines.sv)
 RTLSRC			:= $(wildcard $(RTLSRC_HOME)/rtl/*.sv)
 # TODO: clean this up
 RTLSRC_VLOG_TB_TOP	:= $(basename $(notdir $(RTLSRC_TB_TOP)))
 RTLSRC_VOPT_TB_TOP	:= $(addsuffix _vopt, $(RTLSRC_VLOG_TB_TOP))
 
 # riscv toolchain install path
-RISCV                    ?= ~/.local
+RISCV                    ?= ~/.riscv
 RISCV_EXE_PREFIX         = $(RISCV)/bin/riscv32-unknown-elf-
+
+# firmware vars
 FIRMWARE                 = picorv_firmware/
 FIRMWARE_OBJS		 = $(addprefix picorv_firmware/, start.o \
 				print.o sieve.o multest.o stats.o)
@@ -62,6 +71,12 @@ FIRMWARE_TEST_OBJS       = $(addsuffix .o, \
 				$(basename $(wildcard picorv_tests/*.S)))
 COMPLIANCE_TEST_OBJS	 = $(addsuffix .o, \
 				$(basename $(wildcard riscv_compliance_tests/*.S)))
+
+# csmith vars
+CSMITH_INCLUDE           = ~/.local/include/csmith-2.4.0
+CSMITH_TIMEOUT_REF       = 2
+CSMITH_TIMEOUT_VSIM      = 3000
+CSMITH_TIMEOUT_VERI      = 100
 
 # assume verilator if no target chosen
 .DEFAULT_GOAL := firmware-veri-run
@@ -91,12 +106,26 @@ dpiheader: .build-tb
 	$(VLOG) -work $(VWORK) -l $(VLOG_LOG) -dpiheader $(DPINAME) $(DPISRC)
 
 # verilator testbench compilation
-verilate : $(RTLSRC_VERI_TB) $(RTLSRC_PKG) $(RTLSRC)
-	$(VERILATOR) --cc --sv --exe --trace --Wno-lint --Wno-UNOPTFLAT \
+
+# We first test if the user wants to to vcd dumping. This hacky part is required
+# because we need to conditionally compile the testbench (-DVCD_TRACE) and pass
+# the --trace flags to the verilator call
+ifeq ($(findstring +vcd,$(VERI_FLAGS)),+vcd)
+VERI_TRACE="--trace"
+VERI_CFLAGS+="-DVCD_TRACE"
+endif
+
+verilate: testbench_verilator
+
+testbench_verilator: $(RTLSRC_VERI_TB) $(RTLSRC_PKG) $(RTLSRC)
+	$(VERILATOR) --cc --sv --exe \
+		$(VERI_TRACE) \
+		--Wno-lint --Wno-UNOPTFLAT \
 		--Wno-MODDUP +incdir+$(RTLSRC_INCDIR) --top-module \
 		tb_top_verilator $(RTLSRC_VERI_TB) $(RTLSRC_PKG) $(RTLSRC) \
 		tb_top_verilator.cpp --Mdir $(VERI_DIR) \
-		-CFLAGS "-std=gnu++11"
+		-CFLAGS "-std=gnu++11 $(VERI_CFLAGS)" \
+		$(VERI_COMPILE_FLAGS)
 	$(MAKE) -C $(VERI_DIR) -f Vtb_top_verilator.mk
 	cp $(VERI_DIR)/Vtb_top_verilator testbench_verilator
 
@@ -187,6 +216,105 @@ firmware-clean:
 	rm -vrf $(addprefix picorv_firmware/firmware., elf bin hex map) \
 		$(FIRMWARE_OBJS) $(FIRMWARE_TEST_OBJS) $(COMPLIANCE_TEST_OBJS)
 
+# csmith targets
+csmith/test.c:
+	echo "integer size = 4" > csmith/platform.info
+	echo "pointer size = 4" >> csmith/platform.info
+	$(CSMITH) --no-packed-struct -o csmith/test.c
+	gawk '/Seed:/ {print$$2,$$3;}' csmith/test.c
+
+csmith/test_ref: csmith/test.c
+	gcc -m32 -o csmith/test_ref -w -Os -I $(CSMITH_INCLUDE) csmith/test.c
+
+csmith/test.elf: csmith/test.c csmith/syscalls.c csmith/start.S
+	$(RISCV_EXE_PREFIX)gcc -march=rv32imc -o csmith/test.elf -w -Os \
+		-I $(CSMITH_INCLUDE) \
+		-T csmith/link.ld  \
+		csmith/test.c csmith/syscalls.c csmith/start.S
+	chmod u+x csmith/test.elf
+
+csmith/test.hex: csmith/test.elf
+	$(RISCV_EXE_PREFIX)objcopy -O verilog csmith/test.elf csmith/test.hex
+
+csmith-clean:
+	rm -rf $(addprefix csmith/, test.c test.elf test.hex test_ref)
+
+riscv-fesvr/build.ok:
+	rm -rf riscv-fesvr
+	git clone https://github.com/riscv/riscv-fesvr.git riscv-fesvr
+	+cd riscv-fesvr && git checkout 1c02bd6 && \
+		./configure && make && touch build.ok
+
+riscv-isa-sim/build.ok: riscv-fesvr/build.ok
+	rm -rf riscv-isa-sim
+	git clone https://github.com/riscv/riscv-isa-sim.git riscv-isa-sim
+	cd riscv-isa-sim && git checkout 10ae74e
+	cd riscv-isa-sim && patch -p1 < ../csmith/riscv-isa-sim.diff
+	cd riscv-isa-sim &&
+		LDFLAGS="-L../riscv-fesvr" ./configure --with-isa=RV32IMC
+	+cd riscv-isa-sim
+		&& ln -s ../riscv-fesvr/fesvr . && make && touch build.ok
+
+.PHONY: csmith-spike
+csmith-spike: riscv-fesvr/build.ok riscv-isa-sim/build.ok csmith/test_ref \
+		 csmith/test.elf
+	timeout $(CSMITH_TIMEOUT_REF) ./csmith/test_ref > csmith/output_ref.txt \
+		&& cat csmith/output_ref.txt
+	LD_LIBRARY_PATH="./riscv-isa-sim:./riscv-fesvr" \
+		./riscv-isa-sim/spike csmith/test.elf > csmith/output_sim.txt
+	diff -u csmith/output_ref.txt csmith/output_sim.txt
+
+# run verilator on csmith/test.hex and only return the checksum, if any. We also have
+# a timeout mechanism in place to prevent infinite loops
+.PHONY: csmith-veri-rtl
+csmith-veri-rtl: verilate csmith/test.hex
+csmith-veri-rtl: VERI_FLAGS += "+firmware=csmith/test.hex"
+csmith-veri-rtl:
+	timeout $(CSMITH_TIMEOUT_VERI) ./testbench_verilator $(VERI_FLAGS) \
+	| grep 'checksum' > csmith/output_sim.txt
+
+# run vsim on csmith/test.hex and only return the checksum, if any. We also have
+# a timeout mechanism in place to prevent infinite loops
+.PHONY: csmith-vsim-rtl
+csmith-vsim-rtl: tb-all csmith/test.hex
+csmith-vsim-rtl: ALL_VSIM_FLAGS += "-GBOOT_ADDR=128"
+csmith-vsim-rtl: ALL_VSIM_FLAGS += "+firmware=csmith/test.hex"
+csmith-vsim-rtl:
+	timeout $(CSMITH_TIMEOUT_VSIM) $(VSIM) -work $(VWORK) \
+	$(ALL_VSIM_FLAGS) \
+	$(RTLSRC_VOPT_TB_TOP) -do 'source $(VSIM_SCRIPT); exit -f' \
+	| grep 'checksum' | cut -c 3- > csmith/output_sim.txt
+
+.PHONY: csmith-loop
+csmith-loop: riscv-fesvr/build.ok riscv-isa-sim/build.ok
+# Check if the reference program terminates and if spike produces the same
+# result. Otherwise we just skip the test. Then we check if we produce the same
+# output with the rtl model (ri5cy). Stop on first failed test
+	+set -e; \
+	x() { echo "$$*" >&2; "$$@"; }; \
+	i=1; j=0; k=0;\
+	while true; do \
+		echo; echo; \
+		echo "--- test#$$((i++)) passed:$${j} skipped:$${k} ---"; \
+		x rm -f $(addprefix csmith/, test.hex test.elf \
+			test.c test_ref output_ref.txt output_sim.txt); \
+		x make csmith-spike csmith/test.hex || \
+			{ \
+				echo SKIP; \
+				! ((k++)); \
+				continue; \
+			}; \
+		x rm -f csmith/output_sim.txt; \
+		x make csmith-veri-rtl; \
+		x diff -u csmith/output_ref.txt csmith/output_sim.txt; \
+			echo OK; ! ((j++)); \
+	done
+
+
 # general targets
 .PHONY: clean
-clean: tb-clean verilate-clean firmware-clean
+clean: tb-clean verilate-clean firmware-clean csmith-clean
+
+.PHONY: distclean
+distclean: clean
+	rm -rf riscv-fesvr riscv-isa-sim
